### ISSUE TITLE
[BUG] Zenodo downloads are flaky following the recent Zenodo upgrade

### ISSUE THREAD

**Issue by paddyroddy** [astro-informatics/sleplet#291]
**Describe the Bug**
Occasionally Zenodo will fail to download the data, simply run again if that is the case

**Comment by paddyroddy** [comment]
This doesn't seem to be an issue any more

**Comment by paddyroddy** [comment]
Some kind of timeout is happening again
```
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='zenodo.org', port=443): Read timed out. (read timeout=5)
```

**Comment by magsol** [comment]
Yeah I think I'm running into this problem as well:

```
Downloading file 'EGM2008_Topography_flms_L2190.mat' from 'doi:10.5281/zenodo.7767698/EGM2008_Topography_flms_L2190.mat' to '/Users/user/Library/Caches/sleplet'.
 67%|████████████████████████▋            | 51.2M/76.8M [00:42<00:15, 1.70MB/s]Traceback (most recent call last):
  File "/opt/python/envs/pyopensci-sleplet/lib/python3.11/site-packages/urllib3/response.py", line 737, in _error_catcher
    yield
  File "/opt/python/envs/pyopensci-sleplet/lib/python3.11/site-packages/urllib3/response.py", line 883, in _raw_read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
urllib3.exceptions.IncompleteRead: IncompleteRead(51285834 bytes read, 25522118 more expected)
```

**Comment by paddyroddy** [comment]
Apologies @magsol! This was working fine, until [Zenodo did their big upgrade in October 2023](https://blog.zenodo.org/2023/10/19/2023-10-19-upgrade-issues). It then started working fine, and only recently has been causing issues again.

**Comment by paddyroddy** [comment]
This should be fixed since https://github.com/fatiando/pooch/issues/409
