### ISSUE TITLE
Unknown mat file type in earth example

### ISSUE THREAD

**Issue by klb2** [astro-informatics/sleplet#81]
When trying to run the command `sphere earth -L 128` to reproduce Fig. 2 in the "Sifting Convolution on the Sphere" section, I get the following error message:
```python
Traceback (most recent call last):
  File "/home/karl/Documents/review/sleplet/venv/bin/sphere", line 8, in <module>
    sys.exit(main())
  File "/home/karl/Documents/review/sleplet/src/sleplet/scripts/plotting_on_sphere.py", line 350, in main
    f = COEFFICIENTS[
  File "pydantic/dataclasses.py", line 341, in pydantic.dataclasses._add_pydantic_validation_attributes.new_init
    'unsafe_hash',
  File "/home/karl/Documents/review/sleplet/src/sleplet/functions/flm/earth.py", line 14, in __post_init_post_parse__
    super().__post_init_post_parse__()
  File "/home/karl/Documents/review/sleplet/src/sleplet/functions/f_lm.py", line 16, in __post_init_post_parse__
    super().__post_init_post_parse__()
  File "/home/karl/Documents/review/sleplet/src/sleplet/functions/coefficients.py", line 32, in __post_init_post_parse__
    self.coefficients = self._create_coefficients()
  File "/home/karl/Documents/review/sleplet/src/sleplet/functions/flm/earth.py", line 17, in _create_coefficients
    return create_flm(self.L, smoothing=self.smoothing)
  File "/home/karl/Documents/review/sleplet/src/sleplet/data/other/earth/create_earth_flm.py", line 19, in create_flm
    flm = _load_flm()
  File "/home/karl/Documents/review/sleplet/src/sleplet/data/other/earth/create_earth_flm.py", line 43, in _load_flm
    mat_contents = sio.loadmat(str(_matfile))
  File "/home/karl/Documents/review/sleplet/venv/lib/python3.10/site-packages/scipy/io/matlab/_mio.py", line 226, in loadmat
    MR, _ = mat_reader_factory(f, **kwargs)
  File "/home/karl/Documents/review/sleplet/venv/lib/python3.10/site-packages/scipy/io/matlab/_mio.py", line 74, in mat_reader_factory
    mjv, mnv = _get_matfile_version(byte_stream)
  File "/home/karl/Documents/review/sleplet/venv/lib/python3.10/site-packages/scipy/io/matlab/_miobase.py", line 251, in _get_matfile_version
    raise ValueError('Unknown mat file type, version %s, %s' % ret)
ValueError: Unknown mat file type, version 55, 54
```

**Comment by klb2** [comment]
The same error occurs when running the command for Fig. 3: `sphere harmonic_gaussian -c earth -e ${ell} 1 -L 128`

**Comment by paddyroddy** [comment]
Can you run install [Git LFS](https://git-lfs.com) and then run `git lfs pull` before trying again? I've been considering a move to [pooch](https://github.com/fatiando/pooch) with storing the data on [zenodo](https://zenodo.org/)

**Comment by paddyroddy** [comment]
I'm now using `pooch` so `Git LFS` is no longer required
