### ISSUE TITLE
Cannot load file containing pickled data in south_america example

### ISSUE THREAD

**Issue by klb2** [astro-informatics/sleplet#82]
When running the command `python -m sleplet.plotting.arbitrary.south_america.tiling_south_america` to reproduce Fig. 2 from the "Slepian Scale-Discretised Wavelets on the Sphere" section, I get the following error:

```python
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/karl/Documents/review/sleplet/src/sleplet/plotting/arbitrary/south_america/tiling_south_america.py", line 54, in <module>
    main()
  File "/home/karl/Documents/review/sleplet/src/sleplet/plotting/arbitrary/south_america/tiling_south_america.py", line 35, in main
    slepian = SlepianArbitrary(L, "south_america")
  File "pydantic/dataclasses.py", line 341, in pydantic.dataclasses._add_pydantic_validation_attributes.new_init
    'unsafe_hash',
  File "/home/karl/Documents/review/sleplet/src/sleplet/slepian/slepian_region/slepian_arbitrary.py", line 47, in __post_init_post_parse__
    super().__post_init_post_parse__()
  File "/home/karl/Documents/review/sleplet/src/sleplet/slepian/slepian_functions.py", line 19, in __post_init_post_parse__
    self.mask = self._create_mask()
  File "/home/karl/Documents/review/sleplet/src/sleplet/slepian/slepian_region/slepian_arbitrary.py", line 56, in _create_mask
    return create_mask_region(self.resolution, self.region)
  File "/home/karl/Documents/review/sleplet/src/sleplet/utils/mask_methods.py", line 32, in create_mask_region
    mask = _load_mask(name)
  File "/home/karl/Documents/review/sleplet/src/sleplet/utils/mask_methods.py", line 62, in _load_mask
    mask = np.load(location)
  File "/home/karl/Documents/review/sleplet/venv/lib/python3.10/site-packages/numpy/lib/npyio.py", line 438, in load
    raise ValueError("Cannot load file containing pickled data "
ValueError: Cannot load file containing pickled data when allow_pickle=False
```

**Comment by klb2** [comment]
Same error for `python -m sleplet.plotting.arbitrary.south_america.eigenvalues_south_america` and `sphere slepian_wavelets -e 3 2 ${j} -L 128 -u`

**Comment by paddyroddy** [comment]
Can you run install [Git LFS](https://git-lfs.com) and then run `git lfs pull` before trying again? I've been considering a move to [pooch](https://github.com/fatiando/pooch) with storing the data on [zenodo](https://zenodo.org/)

**Comment by paddyroddy** [comment]
I'm now using `pooch` so `Git LFS` is no longer required
